// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6B0otYW1I0bvhFtX4L1kzw-K_JqYRR6w',
    appId: '1:85019325480:android:d8cc8f5a85a9c6988c311d',
    messagingSenderId: '85019325480',
    projectId: 'osb-project-9307e',
    storageBucket: 'osb-project-9307e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8WWlDZCHfjDQth_LP-idx-uojcg283L4',
    appId: '1:85019325480:ios:546f0cced0816f3a8c311d',
    messagingSenderId: '85019325480',
    projectId: 'osb-project-9307e',
    storageBucket: 'osb-project-9307e.appspot.com',
    iosBundleId: 'com.example.hasApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyDjNzHG2Uwt5rHb-y02PcSzjOjnKUdjs',
    appId: '1:85019325480:web:6831d0d4ccbc54d18c311d',
    messagingSenderId: '85019325480',
    projectId: 'osb-project-9307e',
    authDomain: 'osb-project-9307e.firebaseapp.com',
    storageBucket: 'osb-project-9307e.appspot.com',
    measurementId: 'G-GJXJKQCQGD',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8WWlDZCHfjDQth_LP-idx-uojcg283L4',
    appId: '1:85019325480:ios:546f0cced0816f3a8c311d',
    messagingSenderId: '85019325480',
    projectId: 'osb-project-9307e',
    storageBucket: 'osb-project-9307e.appspot.com',
    iosBundleId: 'com.example.hasApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyDjNzHG2Uwt5rHb-y02PcSzjOjnKUdjs',
    appId: '1:85019325480:web:121c47bfc55ca3818c311d',
    messagingSenderId: '85019325480',
    projectId: 'osb-project-9307e',
    authDomain: 'osb-project-9307e.firebaseapp.com',
    storageBucket: 'osb-project-9307e.appspot.com',
    measurementId: 'G-H981VNDLQP',
  );

}